import {test,expect} from '@playwright/test';
import {strokeData} from '../../apps/web/src/strokeData';
import {sampleStroke} from '../../apps/web/src/traceGeometry';
test.use({channel:'chrome',serviceWorkers:'block',viewport:{width:320,height:700}});
test('published first lesson: tracing persists, river advances, header stays quiet',async({page})=>{
 test.setTimeout(90000);
 if(process.env.TEST_LOCAL_NETWORK==='true')await page.addInitScript(()=>Object.defineProperty(Navigator.prototype,'onLine',{get:()=>true,configurable:true}));
 await page.goto('./');await page.getByRole('button',{name:'开始今天的冒险'}).click();
 await page.getByRole('button',{name:'准备好啦，出发'}).click();
 await page.getByRole('button',{name:'继续探索'}).click();await page.getByRole('button',{name:'继续探索'}).click();
 const trace=page.locator('.trace-character'),board=page.locator('.trace-board');
 await expect(trace).toContainText('描一描 · 妈');await expect(page.locator('.learner-banner')).toHaveCount(0);
 const box=(await board.boundingBox())!,points=sampleStroke(strokeData['妈'].medians[0]);
 const at=(p:readonly [number,number])=>[box.x+p[0]/1024*box.width,box.y+p[1]/1024*box.height] as const;
 await page.mouse.move(...at(points[0]));await page.mouse.down();
 for(let i=1;i<points.length;i+=3)await page.mouse.move(...at(points[i]));
 await page.mouse.move(...at(points.at(-1)!));await page.mouse.up();
 await expect(trace).toHaveAttribute('data-stroke','1');
 await page.reload();await expect(trace).toHaveAttribute('data-stroke','1');
 await page.getByRole('button',{name:'继续探索'}).click();
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'读好了，继续'}).click();
 const river=page.locator('.river-journey'),options=page.locator('.answer-grid');
 await expect(river).toHaveAttribute('data-solved','0');
 await expect(options.getByRole('button',{name:'爸',exact:true})).toBeEnabled({timeout:20000});
 await options.getByRole('button',{name:'爸',exact:true}).click();await expect(river).toHaveAttribute('data-solved','0');
 await options.getByRole('button',{name:'我',exact:true}).click();
 await expect(river).toHaveAttribute('data-solved','1');await expect(page.locator('.activity-top')).toContainText('9/15');
 await page.reload();await expect(river).toHaveAttribute('data-solved','1');
 await page.screenshot({path:'test-results/interaction-published-320.png'});
});
