// Generated by scripts/generate-reading-timings.py; approximate WAV-based cues.
export const readingTimings: Record<string, { text: string; starts: number[] }> = {
  "wo": {
    "text": "我",
    "starts": [
      0.02
    ]
  },
  "word-wo": {
    "text": "我自己",
    "starts": [
      0.02,
      0.309,
      0.609
    ]
  },
  "ba": {
    "text": "爸",
    "starts": [
      0.03
    ]
  },
  "word-ba": {
    "text": "爸爸",
    "starts": [
      0.03,
      0.339
    ]
  },
  "ma": {
    "text": "妈",
    "starts": [
      0.02
    ]
  },
  "word-ma": {
    "text": "妈妈",
    "starts": [
      0.02,
      0.319
    ]
  },
  "family-reading": {
    "text": "爸爸妈妈和我一起看书。",
    "starts": [
      0.03,
      0.309,
      0.589,
      0.878,
      1.267,
      1.556,
      1.836,
      2.115,
      2.444,
      2.724,
      3.003
    ]
  },
  "jia": {
    "text": "家",
    "starts": [
      0.03
    ]
  },
  "word-jia": {
    "text": "家里",
    "starts": [
      0.03,
      0.329
    ]
  },
  "men": {
    "text": "门",
    "starts": [
      0.02
    ]
  },
  "word-men": {
    "text": "大门",
    "starts": [
      0.03,
      0.349
    ]
  },
  "ren": {
    "text": "人",
    "starts": [
      0.02
    ]
  },
  "word-ren": {
    "text": "一个人",
    "starts": [
      0.02,
      0.289,
      0.549
    ]
  },
  "story-home": {
    "text": "我们一家人站在家门口。",
    "starts": [
      0.02,
      0.309,
      0.599,
      0.918,
      1.217,
      1.507,
      1.796,
      2.095,
      2.385,
      2.684,
      2.973
    ]
  },
  "ni": {
    "text": "你",
    "starts": [
      0.02
    ]
  },
  "word-ni": {
    "text": "对面的你",
    "starts": [
      0.03,
      0.279,
      0.539,
      0.798
    ]
  },
  "hao": {
    "text": "好",
    "starts": [
      0.07
    ]
  },
  "word-hao": {
    "text": "真好",
    "starts": [
      0.03,
      0.399
    ]
  },
  "lai": {
    "text": "来",
    "starts": [
      0.02
    ]
  },
  "word-lai": {
    "text": "走过来",
    "starts": [
      0.04,
      0.439,
      0.778
    ]
  },
  "story-welcome": {
    "text": "你来我家，我向你招手说你好。",
    "starts": [
      0.02,
      0.329,
      0.649,
      0.968,
      1.736,
      1.736,
      2.055,
      2.375,
      2.704,
      3.023,
      3.342,
      3.662,
      3.981,
      4.29
    ]
  },
  "xiao": {
    "text": "小",
    "starts": [
      0.03
    ]
  },
  "word-xiao": {
    "text": "小小的",
    "starts": [
      0.04,
      0.359,
      0.678
    ]
  },
  "mao": {
    "text": "猫",
    "starts": [
      0.02
    ]
  },
  "word-mao": {
    "text": "小猫",
    "starts": [
      0.04,
      0.419
    ]
  },
  "gou": {
    "text": "狗",
    "starts": [
      0.03
    ]
  },
  "word-gou": {
    "text": "小狗",
    "starts": [
      0.04,
      0.419
    ]
  },
  "story-pets": {
    "text": "小猫和小狗在草地上玩球。",
    "starts": [
      0.04,
      0.379,
      0.718,
      1.127,
      1.517,
      1.856,
      2.195,
      2.534,
      2.873,
      3.213,
      3.552,
      3.891
    ]
  },
  "shui": {
    "text": "水",
    "starts": [
      0.03
    ]
  },
  "word-shui": {
    "text": "一杯水",
    "starts": [
      0.02,
      0.379,
      0.698
    ]
  },
  "he": {
    "text": "喝",
    "starts": [
      0.11
    ]
  },
  "word-he": {
    "text": "喝一口",
    "starts": [
      0.1,
      0.369,
      0.688
    ]
  },
  "chi": {
    "text": "吃",
    "starts": [
      0.03
    ]
  },
  "word-chi": {
    "text": "吃东西",
    "starts": [
      0.03,
      0.339,
      0.668
    ]
  },
  "story-snack": {
    "text": "小猫喝水，小狗吃饭。",
    "starts": [
      0.04,
      0.389,
      0.818,
      1.167,
      1.517,
      1.517,
      2.305,
      2.704,
      3.053,
      3.442
    ]
  },
  "yu": {
    "text": "鱼",
    "starts": [
      0.02
    ]
  },
  "word-yu": {
    "text": "小鱼",
    "starts": [
      0.04,
      0.389
    ]
  },
  "niao": {
    "text": "鸟",
    "starts": [
      0.02
    ]
  },
  "word-niao": {
    "text": "小鸟",
    "starts": [
      0.04,
      0.459
    ]
  },
  "kan": {
    "text": "看",
    "starts": [
      0.03
    ]
  },
  "word-kan": {
    "text": "看一看",
    "starts": [
      0.03,
      0.329,
      0.659
    ]
  },
  "story-pond": {
    "text": "我看小鱼游，小鸟在树上。",
    "starts": [
      0.02,
      0.409,
      0.768,
      1.117,
      1.477,
      2.285,
      2.285,
      2.644,
      2.993,
      3.352,
      3.702,
      4.051
    ]
  },
  "you": {
    "text": "有",
    "starts": [
      0.02
    ]
  },
  "word-you": {
    "text": "有一个",
    "starts": [
      0.02,
      0.249,
      0.479
    ]
  },
  "zai": {
    "text": "在",
    "starts": [
      0.03
    ]
  },
  "word-zai": {
    "text": "在哪里",
    "starts": [
      0.03,
      0.279,
      0.529
    ]
  },
  "de": {
    "text": "的",
    "starts": [
      0.02
    ]
  },
  "word-de": {
    "text": "谁的",
    "starts": [
      0.03,
      0.299
    ]
  },
  "story-basket": {
    "text": "我的篮子里有一只小猫，小猫在睡觉。",
    "starts": [
      0.02,
      0.319,
      0.619,
      0.918,
      1.217,
      1.527,
      1.826,
      2.125,
      2.424,
      2.724,
      3.502,
      3.502,
      3.801,
      4.101,
      4.4,
      4.699,
      4.999
    ]
  },
  "ri": {
    "text": "日",
    "starts": [
      0.02
    ]
  },
  "word-ri": {
    "text": "太阳",
    "starts": [
      0.03,
      0.369
    ]
  },
  "yue": {
    "text": "月",
    "starts": [
      0.02
    ]
  },
  "word-yue": {
    "text": "月亮",
    "starts": [
      0.02,
      0.339
    ]
  },
  "shan": {
    "text": "山",
    "starts": [
      0.03
    ]
  },
  "word-shan": {
    "text": "高山",
    "starts": [
      0.03,
      0.399
    ]
  },
  "story-sky": {
    "text": "白日里太阳照着山，夜晚月亮挂在山上。",
    "starts": [
      0.04,
      0.349,
      0.668,
      1.018,
      1.337,
      1.656,
      1.966,
      2.285,
      3.053,
      3.053,
      3.372,
      3.692,
      4.001,
      4.34,
      4.659,
      4.979,
      5.298,
      5.607
    ]
  },
  "mu": {
    "text": "木",
    "starts": [
      0.02
    ]
  },
  "word-mu": {
    "text": "树木",
    "starts": [
      0.03,
      0.339
    ]
  },
  "hua": {
    "text": "花",
    "starts": [
      0.11
    ]
  },
  "word-hua": {
    "text": "花朵",
    "starts": [
      0.11,
      0.439
    ]
  },
  "cao": {
    "text": "草",
    "starts": [
      0.03
    ]
  },
  "word-cao": {
    "text": "小草",
    "starts": [
      0.04,
      0.479
    ]
  },
  "story-plants": {
    "text": "树木旁边有小花，小花下面有绿草。",
    "starts": [
      0.03,
      0.349,
      0.748,
      1.088,
      1.417,
      1.736,
      2.145,
      2.923,
      2.923,
      3.253,
      3.642,
      3.971,
      4.29,
      4.62,
      4.939,
      5.258
    ]
  },
  "shang": {
    "text": "上",
    "starts": [
      0.03
    ]
  },
  "word-shang": {
    "text": "上面",
    "starts": [
      0.03,
      0.409
    ]
  },
  "xia": {
    "text": "下",
    "starts": [
      0.03
    ]
  },
  "word-xia": {
    "text": "下面",
    "starts": [
      0.04,
      0.429
    ]
  },
  "da": {
    "text": "大",
    "starts": [
      0.03
    ]
  },
  "word-da": {
    "text": "大大的",
    "starts": [
      0.03,
      0.269,
      0.509
    ]
  },
  "story-positions": {
    "text": "大树上有小鸟，大树下有小猫。",
    "starts": [
      0.03,
      0.359,
      0.698,
      1.038,
      1.377,
      1.706,
      2.045,
      2.045,
      2.844,
      3.183,
      3.512,
      3.851,
      4.19,
      4.52
    ]
  }
};
