import { z } from 'zod';
import {dataExportSchema,deletionRequestSchema,deletionReceiptSchema,deletionStatusSchema,syncPrepareSchema,syncBatchSchema,syncPlanSchema,syncResultSchema,learningChangesSchema,legacyImportSchema, catalogSchema,lessonPackageSchema,familySchema,learnerSchema,learnerInputSchema,learningProgressSchema,learningResultSchema,learningEventSchema,startLearningSchema,mistakeListSchema,reviewQueueSchema } from '@learnbuddy/contracts';

const deleteOperation={summary:'核验当前密码及昵称/邮箱后永久删除；原请求编号可重试，5 次/5 分钟',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(deletionRequestSchema)}}},responses:{'200':{description:'已删除；客户端清理对应离线数据',content:{'application/json':{schema:z.toJSONSchema(deletionReceiptSchema)}}},'400':{description:'确认文字无效'},'401':{description:'登录失效'},'403':{description:'密码或 Origin 无效'},'404':{description:'目标不可访问'},'429':{description:'验证过于频繁'}}};
const exportOperation={summary:'导出当前家长的云端学习事实、内容版本及旧记录；不含身份凭据',security:[{sessionCookie:[]}],responses:{'200':{description:'JSON 数据导出',content:{'application/json':{schema:z.toJSONSchema(dataExportSchema)}}},'401':{description:'需要登录'},'404':{description:'目标不可访问'}}};
export const contentOpenAPI = {
 openapi:'3.1.0',info:{title:'LearnBuddy API',version:'1.6.0'},
 components:{securitySchemes:{sessionCookie:{type:'apiKey',in:'cookie',name:'better-auth.session_token',description:'由 /api/auth/* 管理的 HttpOnly 会话；HTTPS 使用 __Secure- 前缀'}}},
 paths:{
  '/api/v1/catalog-upgrade':{get:{summary:'查询严格追加兼容的目录版本，不改变学习记录',parameters:[{in:'query',name:'from',required:true,schema:{type:'string'}}],responses:{'200':{description:'可使用的 releaseId；不兼容时保留原版本'}}}},
  '/api/v1/learners/{id}/curriculum-upgrade':{post:{summary:'为本人孩子扩展严格兼容的课程目录，保留原课次和答案；需可信 Origin',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['expectedReleaseId'],additionalProperties:false,properties:{expectedReleaseId:{type:'string',pattern:'^[a-z0-9][a-z0-9-]*$'}}}}}},responses:{'200':{description:'升级后或未变化的学习摘要',content:{'application/json':{schema:z.toJSONSchema(learningProgressSchema)}}},'409':{description:'课程版本已变化，请刷新'}}}},
  '/api/v1/account/export':{get:exportOperation},
  '/api/v1/learners/{id}/export':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],get:exportOperation},
  '/api/v1/account':{delete:deleteOperation},
  '/api/v1/deletion-status':{post:{summary:'本机清理凭据仅可查询此账户是否删除，不能读取学习数据或恢复会话；需可信 Origin',requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(deletionStatusSchema)}}},responses:{'200':{description:'deleted 布尔值'},'403':{description:'Origin 无效'}}}},
  '/api/v1/learners/{id}/sync-streams':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],post:{summary:'幂等建立同步流并预登记课次全部题目呈现；需 streamId/sessionId',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(syncPrepareSchema)}}},responses:{'200':{description:'离线准备包',content:{'application/json':{schema:z.toJSONSchema(syncPlanSchema)}}}}}},
  '/api/v1/learners/{id}/events:batch':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],post:{summary:'最多 100 个有序事件；buffered 仅表示收到，applied 才可删除本机队列；冲突流停止',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(syncBatchSchema)}}},responses:{'200':{description:'逐项结果、下一序号和服务端状态',content:{'application/json':{schema:z.toJSONSchema(syncResultSchema)}}},'409':{description:'编号载荷不一致或缺序过多'}}}},
  '/api/v1/learners/{id}/changes':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],get:{summary:'按档案修订号增量返回改变字段及被替换课次的删除标记；未知游标返回 reset',security:[{sessionCookie:[]}],parameters:[{in:'query',name:'cursor',required:true,schema:{type:'integer',minimum:0}}],responses:{'200':{description:'增量或全量重置',content:{'application/json':{schema:z.toJSONSchema(learningChangesSchema)}}}}}},
  '/api/v1/learners/{id}/imports':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],post:{summary:'家长选择孩子后导入；服务端指纹去重，旧对错仅保留为 legacy_import，不制造真实选择/掌握',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(legacyImportSchema)}}},responses:{'200':{description:'accepted、fingerprint、progress'},'409':{description:'已有档案课程版本不兼容'}}},get:{summary:'读取当前孩子的导入凭据',security:[{sessionCookie:[]}],responses:{'200':{description:'来源、指纹、导入时间'}}}},
  '/api/v1/learners/{id}/progress':{get:{summary:'当前孩子的云端课次、累计完成和能力摘要',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],responses:{'200':{description:'云端权威状态；revision 单调递增',content:{'application/json':{schema:z.toJSONSchema(learningProgressSchema)}}},'401':{description:'未登录'},'404':{description:'不存在或不属于当前家庭'}}}},
  '/api/v1/learners/{id}/sessions':{post:{summary:'开始/继续固定版本课次，requestId 去重；mode 区分正式学习与复习',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(startLearningSchema)}}},responses:{'200':{description:'课次和进度',content:{'application/json':{schema:z.toJSONSchema(learningResultSchema)}}},'400':{description:'未解锁或题目无效'},'409':{description:'请求重用或内容版本冲突'}}}},
  '/api/v1/learners/{id}/events':{post:{summary:'在线提交步骤、作答、提示、播放结果或找字；不接受 correct；离线客户端使用 events:batch',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(learningEventSchema)}}},responses:{'200':{description:'事务确认或重复确认',content:{'application/json':{schema:z.toJSONSchema(learningResultSchema)}}},'400':{description:'事件/选项无效'},'409':{description:'旧 revision、事件冲突或题目已作答'}}}},
  '/api/v1/learners/{id}/mistakes':{get:{summary:'分页查看实际选项和答案的错题历史',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}},{in:'query',name:'cursor',schema:{type:'string',format:'uuid'}},{in:'query',name:'status',schema:{type:'string',enum:['active','all']}}],responses:{'200':{description:'每页最多 20 条',content:{'application/json':{schema:z.toJSONSchema(mistakeListSchema)}}}}}},
  '/api/v1/learners/{id}/reviews':{get:{summary:'基础次日复习最多 30 项；指定已完成 lessonId 时返回本课与历史混合练习至多 5 题',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}},{in:'query',name:'lessonId',schema:{type:'string'}}],responses:{'200':{description:'基础复习队列，完整 1/3/7 调度另行实现',content:{'application/json':{schema:z.toJSONSchema(reviewQueueSchema)}}}}}},
  '/api/v1/learners/{id}/learning-settings':{patch:{summary:'家长开放/关闭全部课程，不制造完成或掌握证据',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],requestBody:{required:true,content:{'application/json':{schema:{type:'object',required:['openAllCourses'],additionalProperties:false,properties:{openAllCourses:{type:'boolean'}}}}}},responses:{'200':{description:'最新云端学习摘要'}}}},

  '/api/v1/admin/content':{get:{summary:'管理员：当前版本、草稿与审计记录',security:[{sessionCookie:[]}],responses:{'200':{description:'channel（含 revision）、releases、drafts、audit'},'403':{description:'需要管理员'}}}},
  '/api/v1/admin/drafts':{post:{summary:'从 baseReleaseId 创建私有草稿',security:[{sessionCookie:[]}],responses:{'201':{description:'草稿与 revision'}}}},
  '/api/v1/admin/drafts/{id}':{parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],get:{summary:'读取管理员草稿',security:[{sessionCookie:[]}],responses:{'200':{description:'含 manifest 的草稿'}}},put:{summary:'保存 manifest，必须提交当前 revision',security:[{sessionCookie:[]}],responses:{'200':{description:'已保存，新 revision'},'409':{description:'并发冲突或已经发布'}}}},
  '/api/v1/admin/drafts/{id}/validate':{post:{summary:'校验已保存草稿的内容、引用、时间点、素材文件',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],responses:{'200':{description:'valid、revision、warnings'},'422':{description:'errors 校验失败'}}}},
  '/api/v1/admin/uploads':{post:{summary:'上传最多 20 MB 的 PNG 或 PCM WAV（原始二进制）',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/octet-stream':{schema:{type:'string',format:'binary'}}}},responses:{'201':{description:'sha256、objectKey、bytes、mimeType、durationMs'},'400':{description:'格式无效'},'413':{description:'超过大小限制'}}}},
  '/api/v1/admin/media/{hash}':{get:{summary:'管理员私有素材预览',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'hash',required:true,schema:{type:'string'}}],responses:{'200':{description:'素材二进制'},'403':{description:'需要管理员'}}}},
  '/api/v1/admin/releases':{post:{summary:'事务发布并启用：draftId、revision、channelRevision',security:[{sessionCookie:[]}],responses:{'201':{description:'不可变 releaseId'},'409':{description:'草稿或当前版本已变化'},'422':{description:'内容或素材校验失败'}}}},
  '/api/v1/admin/releases/{id}/activate':{post:{summary:'启用/回滚到已发布版本，提交 channelRevision',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string'}}],responses:{'200':{description:'当前 releaseId'},'409':{description:'当前版本已经变化'},'422':{description:'素材不可用'}}}},
  '/api/v1/me':{get:{summary:'已验证的家长及孩子列表',security:[{sessionCookie:[]}],responses:{'200':{description:'当前家庭',content:{'application/json':{schema:z.toJSONSchema(familySchema)}}},'401':{description:'未登录或邮箱未验证'}}}},
  '/api/v1/learners':{post:{summary:'为当前家庭创建孩子（最多八个）',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(learnerInputSchema)}}},responses:{'201':{description:'孩子档案',content:{'application/json':{schema:z.toJSONSchema(learnerSchema)}}},'400':{description:'昵称无效'},'401':{description:'未登录'},'403':{description:'Origin 无效'},'409':{description:'档案数量达到上限'}}}},
  '/api/v1/learners/{id}':{delete:deleteOperation,parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],get:{summary:'读取本人家庭的孩子',security:[{sessionCookie:[]}],responses:{'200':{description:'孩子档案',content:{'application/json':{schema:z.toJSONSchema(learnerSchema)}}},'401':{description:'未登录'},'404':{description:'不存在或不属于当前家庭'}}},patch:{summary:'修改本人孩子的昵称',security:[{sessionCookie:[]}],requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(learnerInputSchema)}}},responses:{'200':{description:'更新后的档案'},'400':{description:'昵称无效'},'401':{description:'未登录'},'403':{description:'Origin 无效'},'404':{description:'不存在或不属于当前家庭'}}}},
  '/api/v1/learners/{id}/entitlements':{get:{summary:'服务端统一权益策略（当前默认免费）',security:[{sessionCookie:[]}],parameters:[{in:'path',name:'id',required:true,schema:{type:'string',format:'uuid'}}],responses:{'200':{description:'plan、capabilities、dailyPracticeLimit、expiresAt'},'401':{description:'未登录'},'404':{description:'不存在或不属于当前家庭'}}}},
  '/api/v1/admin/access':{get:{summary:'内容管理员身份边界',security:[{sessionCookie:[]}],responses:{'200':{description:'管理员'},'401':{description:'未登录'},'403':{description:'普通家长无权限'}}}},
  '/api/v1/catalog':{get:{summary:'课程目录；指定 releaseId 可恢复原内容版本',parameters:[{in:'query',name:'releaseId',required:false,schema:{type:'string'}}],responses:{'200':{description:'目录',content:{'application/json':{schema:z.toJSONSchema(catalogSchema)}}},'304':{description:'内容未变化'},'404':{description:'版本不可用'}}}},
  '/api/v1/releases/{releaseId}/lessons/{lessonId}':{get:{summary:'单课内容包及素材 URL',parameters:['releaseId','lessonId'].map(name=>({in:'path',name,required:true,schema:{type:'string'}})),responses:{'200':{description:'课程包',content:{'application/json':{schema:z.toJSONSchema(lessonPackageSchema)}}},'304':{description:'内容未变化'},'404':{description:'版本或课程不存在'}}}}
 }
};
