"""Generate word recordings and approximate character cues from voiced WAV frames.

Cues exclude silence, but are estimates, not forced alignment. Regenerate after
changing recordings; production recordings should supply reviewed character cues.
"""
import array
import json
import subprocess
import sys
import wave
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = (root / 'apps/web/src/content.ts').read_text()
lessons = json.loads(source.split('export const lessons: Lesson[] = ', 1)[1].split(';\nexport const characters', 1)[0])
texts = {}
for lesson in lessons:
    for character in lesson['characters']:
        texts[character['audio']] = character['text']
        name = 'word-' + character['id']
        texts[name] = character['word']
        target = root / 'apps/web/public/assets/audio' / (name + '.wav')
        if not target.exists():
            subprocess.run(['say', '-v', 'Tingting', '-r', '140', '-o', str(target),
                            '--data-format=LEI16@22050', character['word']], check=True)
    texts[lesson['story']['audio']] = lesson['story']['text']

timings = {}
for name, text in texts.items():
    with wave.open(str(root / 'apps/web/public/assets/audio' / (name + '.wav'))) as wav:
        assert wav.getnchannels() == 1 and wav.getsampwidth() == 2
        rate = wav.getframerate()
        samples = array.array('h', wav.readframes(wav.getnframes()))
    if sys.byteorder != 'little':
        samples.byteswap()
    hop = round(rate * .01)
    energy = [sum(s * s for s in samples[i:i+hop]) / len(samples[i:i+hop])
              for i in range(0, len(samples), hop)]
    threshold = max(100, max(energy) * .004)
    voiced = [i * hop / rate for i, value in enumerate(energy) if value > threshold]
    assert voiced, name
    spoken = sum(character.isalnum() for character in text)
    index = 0
    starts = []
    for character in text:
        position = min(len(voiced) - 1, int(index * len(voiced) / spoken))
        starts.append(round(voiced[position], 3))
        if character.isalnum():
            index += 1
    timings[name] = {'text': text, 'starts': starts}

(root / 'apps/web/src/readingTimings.ts').write_text(
    '// Generated by scripts/generate-reading-timings.py; approximate WAV-based cues.\n'
    'export const readingTimings: Record<string, { text: string; starts: number[] }> = '
    + json.dumps(timings, ensure_ascii=False, indent=2) + ';\n')
print(f'Generated cues for {len(timings)} recordings.')
