/** Generates an offline, searchable review sheet from the exact UI illustrations. */
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {WordVisual} from '../../apps/web/src/visuals/WordVisual';
import {wordVisual} from '../../apps/web/src/visuals/resolveWordVisual';
const out=process.env.ACCEPTANCE_REPORT_DIR||'验收/2026-09-23-图标优化';
const source=JSON.parse(await readFile('课程设计/1000字课程.json','utf8'));
const words=new Map<string,{lessons:string[],characters:string[]}>();
for(const l of source.lessons)for(const w of l.words){const row=words.get(w.word)||{lessons:[],characters:[]};row.lessons.push(l.id);row.characters.push(w.character);words.set(w.word,row);}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const labels:Record<string,string>={emoji:'词语图标',sketch:'原创简笔画',scene:'词义情境图',color:'色块',count:'计数图',symbol:'符号',context:'陪读提示'};
const audit=[...words].map(([word,row])=>({word,...row,kind:wordVisual(word)?.kind||'context',value:wordVisual(word)?.value||null,description:wordVisual(word)?.description||null}));
const counts:Record<string,number>={};for(const row of audit)counts[row.kind]=(counts[row.kind]||0)+1;
const cards=audit.map(row=>`<article data-kind="${row.kind}"><div class="visual">${renderToStaticMarkup(React.createElement(WordVisual,{word:row.word}))}</div><b>${escape(row.word)}</b>${row.description?`<p class="meaning">${escape(row.description)}</p>`:''}<small>${labels[row.kind]} · ${escape([...new Set(row.lessons)].join('、'))}</small></article>`).join('');
await mkdir(out,{recursive:true});
await writeFile(`${out}/词语素材清单.json`,JSON.stringify({createdAt:new Date().toISOString(),scope:'200 个设计单元的词语去重；原十课另保留已有专用图片',counts,words:audit},null,2)+'\n');
await writeFile(`${out}/素材总览.html`,`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>词语配图优化 · 素材总览</title><style>*{box-sizing:border-box}body{max-width:1280px;margin:auto;padding:24px;background:#f7f6ed;color:#40533d;font:16px/1.7 system-ui}h1{font-size:28px}input,select{font:inherit;padding:10px;border:1px solid #c4cfb5;border-radius:9px;margin:5px 10px 15px 0;background:#fffdf7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:13px}article{text-align:center;border:1px solid #dfe3d1;border-radius:14px;background:#fffdf6;padding:14px 8px}.visual{height:100px;display:flex;align-items:center;justify-content:center}.word-visual-emoji{font-size:58px}.character-scene{width:120px;height:100px}.word-visual-context{font-size:14px;line-height:1.5;color:#7a856d;border:1px dashed #c8d1b9;border-radius:12px;padding:10px}.meaning{font-size:12px;line-height:1.6;color:#596b51;margin:6px 0}small{display:block;font-size:11px;color:#849077}b{display:block;font-size:18px}article[hidden]{display:none}nav{position:sticky;top:0;background:#f7f6edee;padding-top:8px}a{color:#537844}</style><h1>词语配图优化 · 素材总览</h1><p>按完整词语理解含义；动作、关系和抽象词可用具体情境举例。每张情境图附有画意说明，表示一个用法示例，并非词语的全部含义。仍需完整上下文的词保留陪读提示。此页是素材样张，不是学习页截图。</p><p>${Object.entries(counts).map(([k,v])=>`${labels[k]} ${v}`).join(' · ')}；共 ${audit.length} 个不同词语。</p><nav><label>找词语 <input id="q" placeholder="如：萝卜、蝴蝶、因为"></label><label>素材类别 <select id="kind"><option value="">全部</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label></nav><section class="grid">${cards}</section><script>function filter(){const q=document.querySelector('#q').value.trim(),k=document.querySelector('#kind').value;document.querySelectorAll('article').forEach(x=>x.hidden=!(x.innerText.includes(q)&&(!k||x.dataset.kind===k)))}document.querySelector('#q').addEventListener('input',filter);document.querySelector('#kind').addEventListener('change',filter)</script></html>`);
console.log(JSON.stringify({words:audit.length,counts}));
